# Generated by Django 3.1.4 on 2021-01-01 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50)),
                ('phNo', models.CharField(max_length=10)),
                ('experince', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('bloodGroup', models.CharField(max_length=3)),
                ('age', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('phNo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('dname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.doctor')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNo', models.PositiveIntegerField()),
                ('rtype', models.CharField(max_length=50)),
                ('rent', models.PositiveIntegerField()),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.CharField(max_length=50)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patients')),
            ],
        ),
    ]
