# Generated by Django 3.1.4 on 2021-01-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210102_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='mno',
            field=models.CharField(default='1', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomNo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teatment',
            name='tid',
            field=models.CharField(max_length=50),
        ),
    ]
