# Generated by Django 3.1.4 on 2021-01-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210102_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='roomNo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teatment',
            name='tid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
