# Generated by Django 3.1.4 on 2021-01-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20210102_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teatment',
            name='tid',
            field=models.CharField(max_length=50),
        ),
    ]
