# Generated by Django 3.1.4 on 2021-01-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20210102_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='did',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patients',
            name='pid',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='teatment',
            name='tid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
