# Generated by Django 3.1.4 on 2021-01-03 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20210103_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patients', unique=True),
        ),
    ]
