# Generated by Django 3.1.4 on 2021-01-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_rooms_avaliable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='mno',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
