# Generated by Django 3.1.4 on 2021-01-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_auto_20210117_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='did',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Doctor ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experince',
            field=models.IntegerField(verbose_name='Experince'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phNo',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(max_length=50, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=50, null=True, verbose_name='Specialization'),
        ),
    ]
