# Generated by Django 3.1.4 on 2021-01-18 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20210118_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='mname',
            field=models.CharField(max_length=50, verbose_name='Medicine Name'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='mno',
            field=models.CharField(max_length=50, unique=True, verbose_name='Medicine ID'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patients', verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='bloodGroup',
            field=models.CharField(max_length=3, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phNo',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='pid',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='avaliable',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=50, verbose_name='Avaliable'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='pname',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.CASCADE, to='management.patients', verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='rent',
            field=models.PositiveIntegerField(verbose_name='Rent'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='roomNo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='rtype',
            field=models.CharField(max_length=50, verbose_name='Room Type'),
        ),
        migrations.AlterField(
            model_name='teatment',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='teatment',
            name='dname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.doctor', verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='teatment',
            name='pname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.patients', verbose_name='Patient Name'),
        ),
        migrations.AlterField(
            model_name='teatment',
            name='tid',
            field=models.CharField(max_length=50, unique=True, verbose_name='Treatment ID'),
        ),
    ]
