# Generated by Django 3.1.4 on 2021-01-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_doctor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
