# Generated by Django 3.1.4 on 2021-01-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_patients_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
